services:
  # Serviço da API FastAPI
  - type: web
    name: fastapi-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis
      - key: REDIS_PORT
        value: 6379
      - key: DB_TYPE
        value: mariadb
      - key: DB_USER
        value: teste_python
      - key: DB_PASS
        value: teste@1234
      - key: DB_HOST
        fromService:
          name: mariadb
          type: pserv
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: TESTE_PYTHON
      - key: DB_CONNECTOR
        value: pymysql
      - key: JWT_SECRET_KEY
        value: 7s0RscNkUzc0Pugmj8rjPcgeyl1U7IjihSh0DNqNrtc=
    # Porta que o Render expõe automaticamente
    autoDeploy: true

  # Banco MariaDB
  - type: pserv
    name: mariadb
    env: docker
    plan: free
    dockerfilePath: ""
    image: mariadb:11
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        value: HardPass@1234
      - key: MARIADB_DATABASE
        value: TESTE_PYTHON
      - key: MARIADB_USER
        value: teste_python
      - key: MARIADB_PASSWORD
        value: teste@1234
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 1

  # Redis
  - type: redis
    name: redis
    plan: free